import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, IsNull, Repository } from 'typeorm';
import { CreateCiclosTelecomDto } from './dto/create-ciclos-telecom.dto';
import { UpdateCiclosTelecomDto } from './dto/update-ciclos-telecom.dto';
import { CicloTelecom } from './entities/ciclos-telecom.entity';
import { PoolTelecom } from '../pools-telecom/entities/pools-telecom.entity';
import { CapacidadPoolTelecom } from '../pools-telecom/entities/capacidades-pool-telecom.entity';
import { Usuario } from '../usuarios/entities/usuario.entity';
import { BitacoraAuditoriaSistema } from '../bitacora-auditoria-sistema/entities/bitacora-auditoria-sistema.entity';
import type { AuthenticatedUser } from '../auth/decorators/current-user.decorator';

@Injectable()
export class CiclosTelecomService {
  constructor(@InjectRepository(CicloTelecom) private readonly ciclos: Repository<CicloTelecom>, @InjectRepository(PoolTelecom) private readonly pools: Repository<PoolTelecom>, @InjectRepository(CapacidadPoolTelecom) private readonly capacidades: Repository<CapacidadPoolTelecom>, @InjectRepository(Usuario) private readonly usuarios: Repository<Usuario>, @InjectRepository(BitacoraAuditoriaSistema) private readonly bitacora: Repository<BitacoraAuditoriaSistema>, private readonly dataSource: DataSource) {}
  async create(dto: CreateCiclosTelecomDto, user: AuthenticatedUser) { await this.actor(user); const pool = await this.pools.findOne({ where: { id: dto.poolTelecomId, empresaId: user.empresaId } }); if (!pool) throw new NotFoundException('Pool no encontrado'); if (new Date(dto.terminaEn) <= new Date(dto.iniciaEn)) throw new BadRequestException('El ciclo debe terminar después de iniciar'); const open = await this.ciclos.findOne({ where: { empresaId: user.empresaId, poolTelecomId: dto.poolTelecomId, estado: 'abierto' } }); if (open) throw new BadRequestException('El pool ya tiene un ciclo abierto'); const saved = await this.ciclos.save(this.ciclos.create({ ...dto, empresaId: user.empresaId, iniciaEn: new Date(dto.iniciaEn), terminaEn: new Date(dto.terminaEn), estado: 'abierto' })); await this.audit(user, 'CICLOS_TELECOM_CREAR', saved.id, null, saved); return saved; }
  findAll(user: AuthenticatedUser) { return this.ciclos.find({ where: { empresaId: user.empresaId }, order: { iniciaEn: 'DESC' } }); }
  async close(id: string, user: AuthenticatedUser) { return this.dataSource.transaction(async manager => { const cycleRepo = manager.getRepository(CicloTelecom); const capRepo = manager.getRepository(CapacidadPoolTelecom); const auditRepo = manager.getRepository(BitacoraAuditoriaSistema); const cycle = await cycleRepo.findOne({ where: { id, empresaId: user.empresaId }, lock: { mode: 'pessimistic_write' } }); if (!cycle) throw new NotFoundException('Ciclo no encontrado'); if (cycle.estado === 'cerrado') return cycle; const pool = await manager.getRepository(PoolTelecom).findOne({ where: { id: cycle.poolTelecomId, empresaId: user.empresaId } }); if (!pool) throw new NotFoundException('Pool no encontrado'); const capacities = await capRepo.find({ where: { empresaId: user.empresaId, poolTelecomId: cycle.poolTelecomId, estaActiva: true } }); const rollover: Record<string, number> = {}; for (const capacity of capacities) { const available = Math.max(0, Number(capacity.cantidadContratada) + Number(capacity.cantidadRolloverActual) - Number(capacity.cantidadAsignada) - Number(capacity.cantidadConsumida)); const next = capacity.rolloverHabilitado ? Math.min(available, Number(capacity.cantidadRolloverMaxima ?? available)) : 0; capacity.cantidadRolloverActual = next.toFixed(4); capacity.cantidadAsignada = '0'; capacity.cantidadConsumida = '0'; await capRepo.save(capacity); rollover[capacity.tipoCapacidad] = next; } const before = { estado: cycle.estado, rolloverAplicado: cycle.rolloverAplicado }; cycle.estado = 'cerrado'; cycle.cerradoEn = new Date(); cycle.rolloverAplicado = rollover; const saved = await cycleRepo.save(cycle); await auditRepo.save(auditRepo.create({ empresaId: user.empresaId, usuarioActorId: user.userId, accion: 'CICLOS_TELECOM_CERRAR', entidad: 'ciclos_telecom', entidadId: saved.id, valoresAnteriores: before, valoresNuevos: saved as unknown as Record<string, unknown>, resultado: 'exito' })); const nextStart = new Date(cycle.terminaEn); const nextEnd = this.nextRenewalDate(nextStart, pool.diaRenovacion); const nextCycle = await cycleRepo.save(cycleRepo.create({ empresaId: user.empresaId, poolTelecomId: cycle.poolTelecomId, iniciaEn: nextStart, terminaEn: nextEnd, estado: 'abierto' })); return { ...saved, siguienteCiclo: nextCycle }; }); }
  private nextRenewalDate(start: Date, renewalDay: number) { const end = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 1)); const daysInMonth = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate(); end.setUTCDate(Math.min(Math.max(1, renewalDay), daysInMonth)); return end; }
  private async actor(user: AuthenticatedUser) { if (!await this.usuarios.findOne({ where: { id: user.userId, empresaId: user.empresaId, deletedAt: IsNull() } })) throw new NotFoundException('Actor no encontrado'); }
  private async audit(user: AuthenticatedUser, accion: string, id: string, before: unknown, after: unknown) { await this.bitacora.save(this.bitacora.create({ empresaId: user.empresaId, usuarioActorId: user.userId, accion, entidad: 'ciclos_telecom', entidadId: id, valoresAnteriores: before as Record<string, unknown> ?? undefined, valoresNuevos: after as Record<string, unknown> ?? undefined, resultado: 'exito' })); }
}
